services:
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb_data:/data/db

  app:
    build: .
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/contactlist
      SPRING_DATA_MONGODB_DATABASE: contactlist
    volumes:
      - ./app_logs:/app/logs
